version: "3.7"

services:
  app:
    build:
      context: ./docker/php
      args:
        UID: ${APP_UID}
        GID: ${APP_GID}
    tty: true
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
